name: lpp
channels:
  - conda-forge
  - defaults
dependencies:
  - lipyphilic
  - ipywidgets
  - jupyter_contrib_nbextensions
  - widgetsnbextension
  - joblib
  - scikit-learn
  - hmmlearn
  - pytables
  - tabulate
- pip:
     - git+https://github.com/MDAnalysis/mdanalysis/tarball/develop

