name: lpp-test
channels:
  - conda-forge
  - defaults
dependencies:
  - lipyphilic
  - ipywidgets
  - jupyter_contrib_nbextensions
  - widgetsnbextension
  - joblib
  - scikit-learn
  - hmmlearn
  - pytables
  - tabulate
  - pip<19
  - pip:
    - git+https://github.com/MDAnalysis/mdanalysis@develop#egg=mdanalysis&subdirectory=package

