name: lpp-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - lipyphilic
  - ipywidgets
  - jupyter_contrib_nbextensions
  - widgetsnbextension
  - joblib
  - scikit-learn
  - hmmlearn
  - pytables
  - tabulate
